### ISSUE TITLE
add beneficiary endpoint

### ISSUE THREAD

**Issue by grigore-fiodorov** [code4moldova/covid19md-voluntari-server#10]
-add new beneficiary
-edit beneficiary properties
-delete beneficiary(active=false)
-add info for the swagger, here are some properties in this file (new issue ?)https://github.com/code4moldova/covid19md-voluntari-server/blob/fast_endpoints/backend/static/swagger.yaml#L39
-add filter by: name, phone, range/number, date created, created by(new issue)?

some work done in the branch fast_endpoints

**Comment by johnsmithm** [comment]
https://docs.google.com/document/d/1gMwveFTaJlBPL2KiuNhibwInFYJCbyQTK5f-67Oicoc/edit?usp=sharing
