### ISSUE TITLE
add volunteer endpoint

### ISSUE THREAD

**Issue by grigore-fiodorov** [code4moldova/covid19md-voluntari-server#11]
- add new volunteer
- edit volunteer properties
- delete volunteer(active=false)
- add info for the swagger, here are some properties in this file (new issue ?)https://github.com/code4moldova/covid19md-voluntari-server/blob/fast_endpoints/backend/static/swagger.yaml#L39
- add filter by: name, phone, range/number, date created, created by(new issue)?

**Comment by johnsmithm** [comment]
database structure https://docs.google.com/document/d/1gMwveFTaJlBPL2KiuNhibwInFYJCbyQTK5f-67Oicoc/edit?usp=sharing
