### ISSUE TITLE
tg bot not rewrite the questions/comment field

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/covid19md-voluntari-server#53]
- tg bot not rewrite the questions/comment field
- get the old values
- add the telegram bot responses

**Comment by alexciornii** [comment]
@johnsmithm Last point is regarding changes in telegram bot. I'm changing the task and create a new one in appropriate repository.

**Comment by johnsmithm** [comment]
- write the telegram comment to comments fields (the fixer will write his in fixer_comment field)

**Comment by alexciornii** [comment]
telegram comments are already writing in `comments` field
